
name: "Release Docker Image"

on:
  workflow_call:
    inputs:
      docker_image_name:
        type: string
        required: true
      docker_image_tags:
        type: string
        required: true
      docker_build_platform:
        type: string
        required: false
        default: linux/amd64,linux/arm64
      docker_image_readme:
        type: string
        required: false
        default: README.md
      docker_registry_url:
        type: string
        required: false
        default: docker.io
      docker_registry_username:
        type: string
        required: false
      docker_registry_password:
        type: string
        required: false
      git_branch:
        type: string
        required: false

jobs:
  release-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Checkout selected branch"
        if: inputs.git_branch
        run: git checkout "${{ inputs.git_branch }}"

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.docker_registry_url }}
          username: ${{ inputs.docker_registry_username || secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.docker_registry_password || secrets.DOCKERHUB_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: "${{ inputs.docker_image_name }}:${{ inputs.docker_image_tags }}"
          platforms: "${{ inputs.docker_build_platform }}"
