
name: "Release Docker Image"

on:
  workflow_call:
    inputs:
      docker_image_name:
        type: string
        required: true
      docker_image_readme:
        type: string
        required: false
        default: README.md
      docker_registry_url:
        type: string
        required: false
        default: docker.io
      docker_registry_username:
        type: string
        required: false
      docker_registry_password:
        type: string
        required: false

jobs:
  release-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.docker_registry_url }}
          username: ${{ inputs.docker_registry_username || secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.docker_registry_password || secrets.DOCKERHUB_PASSWORD }}
