
name: "Create git tag"

on:
  workflow_call:
    inputs:
      run_before:
        type: string
        required: false
      git_tag:
        type: string
        required: true

jobs:
  release-git-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Run before script"
        if: inputs.run_before
        run: |
          echo "${{ inputs.run_before }}" > ./before_script
          chmod +x ./before_script
          ./before_script
          rm ./before_script
      
      - name: "Create and push git tag ${{ inputs.git_tag }}"
        run: |
          git tag "${{ inputs.git_tag }}"
          git push --tags
