
name: "Deploy Helm Chart"

on:
  workflow_call:
    inputs:
      helm_chart_path:
        type: string
        required: false
        default: chart/
      helm_chart_values:
        type: string
        required: false
      helm_release_name:
        type: string
        required: true
      helm_version:
        type: string
        required: true
      k8s_namespace:
        type: string
        required: true
    secrets:
        k8s_config:
          required: true

jobs:
  install-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: azure/setup-helm@v3
        with:
           version: "${{ inputs.helm_version }}"

      - name: "Create k8s config"
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.k8s_config }}" > ~/.kube/config
      
      - name: "Deploy chart"
        run: |
          echo "${{ inputs.helm_chart_values }}"                                                \
            | helm upgrade "${{ inputs.helm_release_name }}" "${{ inputs.helm_chart_path }}"    \
              --install --values "-" --namespace "${{ inputs.k8s_namespace }}"
      
      - name: "Delete k8s config"
        run: rm ~/.kube/config
