
name: "Release Python Package"

on:
  workflow_call:
    inputs:
      git_tag:
        type: string
        required: true
      python_version:
        type: string
        required: true
    secrets:
      pypi_token:
        required: true

jobs:
  release-python-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.git_tag }}

      - uses: actions/setup-python@v4.7.1
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install build dependencies
        run: pip install build twine

      - name: Install python janeiro package
        run: pip install .
      
      - name: Build python janeiro package
        run: python -m build

      - name: Distribute janeiro package on PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.11
        with:
          password: ${{ secrets.pypi_token }}
